/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package processing;

import org.junit.jupiter.api.Test;
import processing.core.PApplet;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "Proccessing Fail");
    }
}
